import LeanTest
import RelativeDistance

open LeanTest

def relativeDistanceTests : TestSuite :=
  (TestSuite.empty "RelativeDistance")
  |>.addTest "Direct parent-child relation" (do
      return assertEqual (some 1) (RelativeDistance.degreeOfSeparation [("Tomoko", ["Aditi"]), ("Vera", ["Tomoko"])] "Vera" "Tomoko"))
  |>.addTest "Sibling relationship" (do
      return assertEqual (some 1) (RelativeDistance.degreeOfSeparation [("Dalia", ["Olga","Yassin"])] "Olga" "Yassin"))
  |>.addTest "Two degrees of separation, grandchild" (do
      return assertEqual (some 2) (RelativeDistance.degreeOfSeparation [("Khadija", ["Mateo"]), ("Mateo", ["Rami"])] "Khadija" "Rami"))
  |>.addTest "Unrelated individuals" (do
      return assertEqual none (RelativeDistance.degreeOfSeparation [("Kaito", ["Elif"]), ("Priya", ["Rami"])] "Priya" "Kaito"))
  |>.addTest "Complex graph, cousins" (do
      return assertEqual (some 9) (RelativeDistance.degreeOfSeparation [("Aditi", ["Nia"]), ("Nia", ["Antonio"]), ("Aiko", ["Bao","Carlos"]), ("Bao", ["Dalia","Elias"]), ("Carlos", ["Fatima","Gustavo"]), ("Dalia", ["Hassan","Isla"]), ("Elias", ["Javier"]), ("Boris", ["Oscar"]), ("Oscar", ["Bianca"]), ("Fatima", ["Khadija","Liam"]), ("Gustavo", ["Mina"]), ("Celine", ["Priya"]), ("Priya", ["Cai"]), ("Hassan", ["Noah","Olga"]), ("Isla", ["Pedro"]), ("Diego", ["Qi"]), ("Qi", ["Dimitri"]), ("Javier", ["Quynh","Ravi"]), ("Elif", ["Rami"]), ("Rami", ["Ewa"]), ("Farah", ["Sven"]), ("Sven", ["Fabio"]), ("Khadija", ["Sofia"]), ("Liam", ["Tariq","Uma"]), ("Giorgio", ["Tomoko"]), ("Tomoko", ["Gabriela"]), ("Mina", ["Viktor","Wang"]), ("Hana", ["Umar"]), ("Umar", ["Helena"]), ("Uma", ["Giorgio"]), ("Noah", ["Xiomara"]), ("Olga", ["Yuki"]), ("Ian", ["Vera"]), ("Vera", ["Igor"]), ("Pedro", ["Zane","Aditi"]), ("Quynh", ["Boris"]), ("Ravi", ["Celine"]), ("Jing", ["Wyatt"]), ("Wyatt", ["Jun"]), ("Kaito", ["Xia"]), ("Xia", ["Kim"]), ("Sofia", ["Diego","Elif"]), ("Leila", ["Yassin"]), ("Yassin", ["Lucia"]), ("Tariq", ["Farah"]), ("Mateo", ["Zara"]), ("Zara", ["Mohammed"]), ("Viktor", ["Hana","Ian"]), ("Wang", ["Jing"]), ("Xiomara", ["Kaito"]), ("Yuki", ["Leila"]), ("Zane", ["Mateo"])] "Dimitri" "Fabio"))
  |>.addTest "Complex graph, no shortcut, far removed nephew" (do
      return assertEqual (some 14) (RelativeDistance.degreeOfSeparation [("Aditi", ["Nia"]), ("Nia", ["Antonio"]), ("Aiko", ["Bao","Carlos"]), ("Bao", ["Dalia","Elias"]), ("Carlos", ["Fatima","Gustavo"]), ("Dalia", ["Hassan","Isla"]), ("Elias", ["Javier"]), ("Boris", ["Oscar"]), ("Oscar", ["Bianca"]), ("Fatima", ["Khadija","Liam"]), ("Gustavo", ["Mina"]), ("Celine", ["Priya"]), ("Priya", ["Cai"]), ("Hassan", ["Noah","Olga"]), ("Isla", ["Pedro"]), ("Diego", ["Qi"]), ("Qi", ["Dimitri"]), ("Javier", ["Quynh","Ravi"]), ("Elif", ["Rami"]), ("Rami", ["Ewa"]), ("Farah", ["Sven"]), ("Sven", ["Fabio"]), ("Khadija", ["Sofia"]), ("Liam", ["Tariq","Uma"]), ("Giorgio", ["Tomoko"]), ("Tomoko", ["Gabriela"]), ("Mina", ["Viktor","Wang"]), ("Hana", ["Umar"]), ("Umar", ["Helena"]), ("Uma", ["Giorgio"]), ("Noah", ["Xiomara"]), ("Olga", ["Yuki"]), ("Ian", ["Vera"]), ("Vera", ["Igor"]), ("Pedro", ["Zane","Aditi"]), ("Quynh", ["Boris"]), ("Ravi", ["Celine"]), ("Jing", ["Wyatt"]), ("Wyatt", ["Jun"]), ("Kaito", ["Xia"]), ("Xia", ["Kim"]), ("Sofia", ["Diego","Elif"]), ("Leila", ["Yassin"]), ("Yassin", ["Lucia"]), ("Tariq", ["Farah"]), ("Mateo", ["Zara"]), ("Zara", ["Mohammed"]), ("Viktor", ["Hana","Ian"]), ("Wang", ["Jing"]), ("Xiomara", ["Kaito"]), ("Yuki", ["Leila"]), ("Zane", ["Mateo"])] "Lucia" "Jun"))
  |>.addTest "Complex graph, some shortcuts, cross-down and cross-up, cousins several times removed, with unrelated family tree" (do
      return assertEqual (some 12) (RelativeDistance.degreeOfSeparation [("Aditi", ["Nia"]), ("Nia", ["Antonio"]), ("Aiko", ["Bao","Carlos"]), ("Bao", ["Dalia"]), ("Carlos", ["Fatima","Gustavo"]), ("Dalia", ["Hassan","Isla"]), ("Boris", ["Oscar"]), ("Oscar", ["Bianca"]), ("Fatima", ["Khadija","Liam"]), ("Gustavo", ["Mina"]), ("Celine", ["Priya"]), ("Priya", ["Cai"]), ("Hassan", ["Noah","Olga"]), ("Isla", ["Pedro"]), ("Diego", ["Qi"]), ("Qi", ["Dimitri"]), ("Elif", ["Rami"]), ("Rami", ["Ewa"]), ("Farah", ["Sven"]), ("Sven", ["Fabio"]), ("Khadija", ["Sofia"]), ("Liam", ["Tariq","Uma"]), ("Giorgio", ["Tomoko"]), ("Tomoko", ["Gabriela"]), ("Mina", ["Viktor","Wang"]), ("Hana", ["Umar"]), ("Umar", ["Helena"]), ("Uma", ["Giorgio"]), ("Noah", ["Xiomara"]), ("Olga", ["Yuki"]), ("Ian", ["Vera"]), ("Vera", ["Igor"]), ("Pedro", ["Zane","Aditi"]), ("Javier", ["Quynh","Ravi"]), ("Quynh", ["Boris"]), ("Ravi", ["Celine"]), ("Jing", ["Wyatt"]), ("Wyatt", ["Jun"]), ("Kaito", ["Xia"]), ("Xia", ["Kim"]), ("Sofia", ["Diego","Elif"]), ("Leila", ["Yassin"]), ("Yassin", ["Lucia"]), ("Tariq", ["Farah"]), ("Mateo", ["Zara"]), ("Zara", ["Mohammed"]), ("Viktor", ["Hana","Ian"]), ("Wang", ["Jing"]), ("Xiomara", ["Kaito"]), ("Yuki", ["Leila"]), ("Zane", ["Mateo"])] "Wyatt" "Xia"))

def main : IO UInt32 := do
  runTestSuitesWithExitCode [relativeDistanceTests]
