name = "resistor-color"
version = "0.1.0"
defaultTargets = ["ResistorColorTest"]
testDriver = "ResistorColorTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ResistorColor"

[[lean_exe]]
name = "ResistorColorTest"
root = "ResistorColorTest"
